src/main/java/com/twentyone/steachserver/domain/auth/model/AuthCode.java, src/main/java/com/twentyone/steachserver/domain/auth/model/LoginCredential.java, src/main/java/com/twentyone/steachserver/domain/classroom/model/Classroom.java, src/main/java/com/twentyone/steachserver/domain/curricula/model/Curricula.java, src/main/java/com/twentyone/steachserver/domain/curricula/model/CurriculaInformation.java, src/main/java/com/twentyone/steachserver/domain/curricula/model/CurriculaSchedule.java, src/main/java/com/twentyone/steachserver/domain/lecture/model/Lecture.java, src/main/java/com/twentyone/steachserver/domain/lectureStudents/model/LecturesStudents.java, src/main/java/com/twentyone/steachserver/domain/member/model/Admin.java, src/main/java/com/twentyone/steachserver/domain/member/model/Student.java, src/main/java/com/twentyone/steachserver/domain/member/model/Teacher.java, src/main/java/com/twentyone/steachserver/domain/studentCurricula/model/StudentsCurricula.java
바뀐 erd에 따라 엔티티 매핑을 수정하였습니다.
> 어떤 작업을 했는지 간단하게 작성
엔티티 매핑을 바뀐 erd에 맞게 수정하였습니다.
<br><br>
엔티티 매핑을 바뀐 erd에 맞게 수정하였습니다.
<br><br>
10분
<br><br>
오류 있으면 확인해주세요
<br><br>
<br><br>
>> example
>> - Close #이슈번호
<br><br><br>
---
=> refactor: 엔티티 매핑 수정

build.gradle, src/main/java/com/twentyone/steachserver/config/SwaggerConfiguration.java, src/main/java/com/twentyone/steachserver/config/security/JwtAuthenticationFilter.java, src/main/java/com/twentyone/steachserver/config/security/applicationConfig.java, src/main/java/com/twentyone/steachserver/config/security/securityConfiguration.java, src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthCodeController.java, src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthController.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/AuthCodeAuthenticateRequest.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/AuthCodeAuthenticateResponse.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/AuthCodeRequest.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/AuthCodeResponse.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/LoginDto.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/LoginResponseDto.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/SignUpDto.java, src/main/java/com/twentyone/steachserver/domain/auth/model/AuthCode.java, src/main/java/com/twentyone/steachserver/domain/auth/model/LoginCredential.java, src/main/java/com/twentyone/steachserver/domain/auth/repository/AuthCodeRepository.java, src/main/java/com/twentyone/steachserver/domain/auth/repository/LoginCredentialRepository.java, src/main/java/com/twentyone/steachserver/domain/auth/service/AuthCodeService.java, src/main/java/com/twentyone/steachserver/domain/auth/service/AuthCodeServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/auth/service/AuthService.java, src/main/java/com/twentyone/steachserver/domain/auth/service/AuthServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/auth/service/JwtService.java, src/main/java/com/twentyone/steachserver/domain/auth/util/RandomStringGenerator.java, src/main/java/com/twentyone/steachserver/domain/member/model/Student.java, src/main/java/com/twentyone/steachserver/domain/member/model/Teacher.java, src/main/java/com/twentyone/steachserver/domain/member/repository/TeacherRepository.java
누락된 swagger, 로그인 관련 코드 추가
> 어떤 작업을 했는지 간단하게 작성
누락된 코드를 다시 추가했습니다.
<br><br>
swagger, 로그인 관련 누락 코드 추가했습니다.
<br><br>
1분
<br><br>
<br><br>
<br><br>
>> example
>> - Close #이슈번호
<br><br><br>
---
=> fix: 누락 코드 추가

src/main/java/com/twentyone/steachserver/domain/auth/model/LoginCredential.java, src/main/java/com/twentyone/steachserver/domain/auth/service/AuthServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/classroom/model/Classroom.java, src/main/java/com/twentyone/steachserver/domain/curriculum/model/Curriculum.java, src/main/java/com/twentyone/steachserver/domain/curriculum/model/CurriculumDetail.java, src/main/java/com/twentyone/steachserver/domain/lecture/model/Lecture.java, src/main/java/com/twentyone/steachserver/domain/lecture/repository/LectureRepository.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/lectureStudent/model/LectureStudent.java, src/main/java/com/twentyone/steachserver/domain/member/model/Admin.java, src/main/java/com/twentyone/steachserver/domain/member/model/Student.java, src/main/java/com/twentyone/steachserver/domain/member/model/Teacher.java, src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizResponseDto.java, src/main/java/com/twentyone/steachserver/domain/quiz/model/Quiz.java, src/main/java/com/twentyone/steachserver/domain/studentCurriculum/model/StudentCurriculum.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/model/StudentQuiz.java, src/main/resources/sql/schema.sql
> 어떤 작업을 했는지 간단하게 작성
- 컬럼명 변경에 따른 변수명 변경 및 메서드명 변경 
- 엔티티 상속 관계 추가 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
>> example
>> - Close #이슈번호
<br><br><br>
---
=> refactor: erd 변경에 따른 변경 및 엔티티 상속 관계 추가 

src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumDetailResponse.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumListResponse.java, src/main/java/com/twentyone/steachserver/domain/curriculum/model/Curriculum.java, src/main/java/com/twentyone/steachserver/domain/curriculum/model/CurriculumDetail.java, src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumRepository.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentCurriculum/repository/StudentCurriculumRepository.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/repository/StudentLectureQueryRepository.java
저장 에러 수정, 커리큘럼 신청 에러 수정 등
> 어떤 작업을 했는지 간단하게 작성
커리큘럼 관련 에러 수정함
<br><br>
저장 에러 수정, curriculum이 curriculum_detail 안불러오는 에러 수정, 커리큘럼 신청 에러 수정
<br><br>
5분
<br><br>
<br><br>
<br><br>
>> example
>> - Close #이슈번호
<br><br><br>
---
=> fix: 커리큘럼 관련 에러 수정

build.gradle, src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthController.java, src/main/java/com/twentyone/steachserver/domain/auth/model/LoginCredential.java, src/main/java/com/twentyone/steachserver/domain/classroom/model/Classroom.java, src/main/java/com/twentyone/steachserver/domain/curriculum/model/CurriculumDetail.java, src/main/java/com/twentyone/steachserver/domain/lecture/model/Lecture.java, src/main/java/com/twentyone/steachserver/domain/member/model/Admin.java, src/main/java/com/twentyone/steachserver/domain/member/model/Student.java, src/main/java/com/twentyone/steachserver/domain/member/model/Teacher.java, src/main/java/com/twentyone/steachserver/domain/quiz/model/Quiz.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/model/StudentLecture.java
> 어떤 작업을 했는지 간단하게 작성 😀
swagger 버전 변경, 디비 스키마와 안맞는 부분 검증
<br><br>
swagger 버전 최신버전으로 변경했고,
디비 스키마 sql파일이랑 하나하나 비교하면서 타입 모두 맞췄습니다. statistic 빼고 모두 반영된 상태입니다.
<br><br>
10분
<br><br>
스키마 싹 수정하고 swagger로 기능 모두 테스트해보려고 했는데 돌아가는 기능이 하나도 없었습니다. 엔티티 매핑이 문제가 아니라 그냥 동작하는 기능이 하나도 없습니다. (service 빈 주입도 안돼있습니다) API 배포 전까지는 만든 기능 테스트 꼭 해야할 것 같아요. 
<br><br>
<br><br>
>> example
>> - Close #이슈번호  
>> ex) Close [#1](https://github.com/TEAM-2NE1/steach-server/pull/2)
<br><br><br>
---
=> swagger 버전 변경, 디비 스키마와 안맞는 부분 검증

src/main/java/com/twentyone/steachserver/domain/classroom/controller/ClassroomController.java, src/main/java/com/twentyone/steachserver/domain/classroom/service/ClassroomServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/lecture/dto/update/UpdateLectureRequestDto.java, src/main/java/com/twentyone/steachserver/domain/lecture/model/Lecture.java, src/main/java/com/twentyone/steachserver/domain/lecture/repository/LectureQueryRepository.java, src/main/java/com/twentyone/steachserver/domain/quiz/controller/QuizController.java, src/main/java/com/twentyone/steachserver/domain/statistic/controller/StatisticController.java, src/main/java/com/twentyone/steachserver/domain/statistic/service/StatisticServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/model/StudentLecture.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/repository/StudentLectureQueryRepository.java
API 에러 수정
<br><br>
에러수정
<br><br>
3분
<br><br>
<br><br>
<br><br>
<hr>
=> fix: 안돌아가는 부분 수정

src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumDetailResponse.java, src/main/java/com/twentyone/steachserver/domain/curriculum/model/CurriculumDetail.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/test/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImplTest.java
커리큘럼 테스트코드 작성, 컬럼 타입 변경
<br><br>
커리큘럼 테스트코드 작성, 컬럼 타입 변경
<br><br>
3분
<br><br>
<br><br>
<br><br>
<hr>
=> 커리큘럼 테스트코드 작성, 컬럼 타입 변경

src/main/java/com/twentyone/steachserver/domain/curriculum/model/CurriculumDetail.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/lecture/validator/LectureValidator.java, src/main/java/com/twentyone/steachserver/domain/quiz/controller/QuizController.java, src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizByLectureDto.java, src/main/java/com/twentyone/steachserver/domain/quiz/model/Quiz.java, src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/controller/StudentLectureController.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/model/StudentLecture.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/service/StudentLectureServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/controller/StudentQuizController.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/repository/StudentQuizRepository.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/service/StudentQuizServiceImpl.java
- 최종 강의 메서드 제외한 코드들 테스트 완료
- 예외로직 및 검증코드 추가
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 최종 강의 메서드 제외한 코드들 테스트 완료

src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/curriculum/validator/CurriculumValidator.java
- 검증 로직 추가
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> feat: MaxAttendees의 입력 대한 검증로직 추가

src/main/java/com/twentyone/steachserver/config/SwaggerConfiguration.java, src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthCodeController.java, src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthController.java, src/main/java/com/twentyone/steachserver/domain/auth/error/ForbiddenException.java, src/main/java/com/twentyone/steachserver/domain/classroom/controller/ClassroomController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumDetailResponse.java, src/main/java/com/twentyone/steachserver/domain/curriculum/model/CurriculumDetail.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/lecture/controller/LectureController.java, src/main/java/com/twentyone/steachserver/domain/member/memberController/StudentController.java, src/main/java/com/twentyone/steachserver/domain/member/memberController/TeacherController.java, src/main/java/com/twentyone/steachserver/domain/quiz/controller/QuizController.java, src/main/java/com/twentyone/steachserver/domain/statistic/controller/StatisticController.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/controller/StudentLectureController.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/controller/StudentQuizController.java, src/test/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImplTest.java, src/test/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceIntegrationTest.java, src/test/java/com/twentyone/steachserver/domain/quiz/service/QuizIntegrationTest.java
- 테스트 코드 작성 & 오류 수정
- swagger 문서  정렬
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 테스트코드 작성 및 오류수정, swagger 문서 정렬

src/main/java/com/twentyone/steachserver/GlobalControllerAdvice.java, src/main/java/com/twentyone/steachserver/config/security/securityConfiguration.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/JwtExceptionFilter.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/JwtExceptionResponse.java, src/main/java/com/twentyone/steachserver/domain/auth/service/JwtService.java, src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumAddRequest.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumDetailResponse.java, src/main/java/com/twentyone/steachserver/domain/curriculum/error/DuplicatedCurriculumRegistrationException.java, src/main/java/com/twentyone/steachserver/domain/curriculum/model/CurriculumDetail.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumService.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/curriculum/validator/CurriculumValidator.java, src/main/java/com/twentyone/steachserver/domain/lecture/dto/LectureListResponseDto.java, src/main/java/com/twentyone/steachserver/domain/lecture/dto/LectureResponseDto.java, src/main/java/com/twentyone/steachserver/domain/lecture/repository/LectureRepository.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureService.java, src/main/java/com/twentyone/steachserver/domain/studentCurriculum/repository/StudentCurriculumRepository.java, src/test/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImplTest.java, src/test/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceIntegrationTest.java, src/test/java/com/twentyone/steachserver/domain/quiz/service/QuizChoiceServiceImplTest.java, src/test/java/com/twentyone/steachserver/domain/quiz/service/QuizIntegrationTest.java
calculatedFocusRatio 0에러 발생 해결
- 머지한 내용 다시 불러오기 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: merge request

src/main/java/com/twentyone/steachserver/domain/lecture/controller/LectureController.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureService.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/member/model/Teacher.java
- 선생님의 봉사활동 시간 추가 메서드 추가
<br><br>
마지막 강의시, 강의가 정상적으로 마무리 되면 봉사활동이 추가됨
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> feat: 선생님의 봉사활동 시간 추가 메서드 추가

src/main/java/com/twentyone/steachserver/GlobalControllerAdvice.java, src/main/java/com/twentyone/steachserver/config/WebConfig.java, src/main/java/com/twentyone/steachserver/domain/lecture/controller/LectureController.java, src/main/java/com/twentyone/steachserver/domain/lecture/error/LectureTimeNotYetException.java, src/main/java/com/twentyone/steachserver/domain/statistic/service/StatisticServiceImpl.java, src/main/java/com/twentyone/steachserver/global/error/ErrorCode.java, src/main/java/com/twentyone/steachserver/global/error/ErrorResponseDto.java
ErrorCode, ErrorResponseDto 생성
<br><br>
ErrorCode, ErrorResponseDto 생성
<br><br>
10분
<br><br>
<br><br>
<br><br>
<hr>
=> feat: ErrorCode, ErrorResponseDto 생성

src/main/java/com/twentyone/steachserver/domain/lecture/controller/LectureController.java, src/main/java/com/twentyone/steachserver/domain/statistic/controller/StatisticController.java, src/main/java/com/twentyone/steachserver/domain/statistic/dto/StatisticsByCurriculumCategory.java, src/main/java/com/twentyone/steachserver/domain/statistic/model/RadarChartStatistic.java, src/main/java/com/twentyone/steachserver/domain/statistic/model/mongo/GPTDataByLecture.java, src/main/java/com/twentyone/steachserver/domain/statistic/repository/GPTDataByLectureMongoRepository.java, src/main/java/com/twentyone/steachserver/domain/statistic/repository/LectureStatisticMongoRepository.java, src/main/java/com/twentyone/steachserver/domain/statistic/service/StatisticService.java, src/main/java/com/twentyone/steachserver/domain/statistic/service/StatisticServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/repository/StudentLectureQueryRepository.java
- 통계로직 오류 해결
<br><br>
레이더차트 점수관련 통계로직 해결 및
통계 겹쳐서 쌓이는 문제 기존 값지우고 해결하는 방식으로 변경
<br><br>
<br><br>
다음 작업에서 트래픽 작업등 방식을 통해
연속으로 누르는 값에 대해서 요청 받지않게 해결해야함.
<br><br>
<br><br>
<hr>
=> refactor: 통계로직 오류 해결

src/main/java/com/twentyone/steachserver/domain/auth/dto/LoginResponseDto.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/Role.java, src/main/java/com/twentyone/steachserver/domain/auth/service/AuthServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumDetailResponse.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumListResponse.java, src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumSearchRepository.java, src/main/java/com/twentyone/steachserver/domain/lecture/repository/LectureRepository.java
커리큘럼 검색 에러 수정, 회원가입, 로그인 시 회원정보 추가
<br><br>
커리큘럼 검색 에러 수정, 회원가입, 로그인 시 회원정보 추가
<br><br>
10분
<br><br>
<br><br>
<br><br>
<hr>
=> 커리큘럼 검색 에러 수정, 회원가입, 로그인 시 회원정보 추가

src/main/java/com/twentyone/steachserver/domain/lecture/dto/CompletedLecturesResponseDto.java, src/main/java/com/twentyone/steachserver/domain/lecture/dto/LectureBeforeStartingResponseDto.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/quiz/controller/QuizController.java, src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizzesResponseDto.java, src/main/java/com/twentyone/steachserver/domain/statistic/repository/LectureStatisticMongoRepository.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/repository/StudentLectureQueryRepository.java
- 최종 강의 DTO 값 중복 및 잘못 나오는 오류 해결
- 강의에대한 통계값 재대로 나오게 변경
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> Fix: lecture statictics

src/main/java/com/twentyone/steachserver/GlobalControllerAdvice.java, src/main/java/com/twentyone/steachserver/config/security/securityConfiguration.java, src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthController.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/CheckUsernameAvailableResponse.java, src/main/java/com/twentyone/steachserver/domain/auth/error/AuthCodeAlreadyInUseException.java, src/main/java/com/twentyone/steachserver/domain/auth/model/AuthCode.java, src/main/java/com/twentyone/steachserver/domain/auth/repository/LoginCredentialRepository.java, src/main/java/com/twentyone/steachserver/domain/auth/service/AuthService.java, src/main/java/com/twentyone/steachserver/domain/auth/service/AuthServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/statistic/controller/StatisticController.java, src/main/java/com/twentyone/steachserver/global/error/ErrorCode.java
- 아이디 중복확인 API 구현
- AuthCodeAlreadyInUseException 커스텀 exception 생성)
<br><br>
- 프론트 통신 과정에서 근본없는 500 status RuntimeException 메시지="에러"  발생
- 이유는 잠시 RuntimeException으로 지정해둔 코드때문이었음
<br><br>
5분
<br><br>
<br><br>
<br><br>
<hr>
=> 프론트 통신과정 오류 수정, 커스텀 exception 생성

src/main/java/com/twentyone/steachserver/config/security/ApplicationConfig.java, src/main/java/com/twentyone/steachserver/config/security/SecurityConfiguration.java, src/main/java/com/twentyone/steachserver/config/security/securityConfiguration.java, src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculaOrderType.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumListInOrderResponseDto.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/SimpleCurriculumDto.java, src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumSearchRepository.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumService.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/statistic/controller/StatisticController.java
- 인기 강의 조회 및 최신 강의 조회 기능 추가
- 권한 없는 사용자에게 보여줄 페이지를 위한 권한 설정 변경
- 클래스명 소문자에서 대문자로 변환
<br><br>
권한 없는 사용자에게 보여줄 페이지를 위한 권한 설정 변경에 대해서
커리큘럼 조회에 대해서는 비회원도 가능했으면 좋겠는 마음과
커리큘럼에 대한 강의 조회도 가능했으면 좋겠습니다 
그러하여 변경하였습니다.
인기 강의 조회 및 최신 강의 조회를 따로 만든 이유는 프론트에서 편하게 쓰라고 입니다!
+ 전부를 받을 필요 없이 메인 페이지에 보여줄 정보만 넣어서 보내주기 위해서
<br><br>
5m
<br><br>
혹시 클래스를 소문자로 쓴 이유가 또 있을까요?
<br><br>
<br><br>
<hr>
=> feat: 커리큘럼 관련 기능 추가 및 관련 권한 작업

src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthCodeController.java, src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumListResponse.java, src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumRepository.java, src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumSearchRepository.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumService.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/member/memberController/StudentController.java, src/main/java/com/twentyone/steachserver/domain/member/memberController/TeacherController.java, src/main/java/com/twentyone/steachserver/domain/member/model/Student.java, src/main/java/com/twentyone/steachserver/domain/member/model/Teacher.java, src/main/java/com/twentyone/steachserver/domain/studentCurriculum/repository/StudentCurriculumRepository.java, src/main/java/com/twentyone/steachserver/global/dto/PageableDto.java, src/test/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceIntegrationTest.java
- 커리큘럼 조회/검색 페이징 추가
- 회원정보 수정관련 null처리
- swagger문서 작성
<br><br>
이전에 프론트엔드분들과 회의를 하면서 페이징을 넣는다고 말하였는데 기능개발할 때 까먹었습니다. 뒤늦게 추가했습니다.
(최신과 인기 커리큘럼 조회는 내일 회의 후 추가하겠습니다!)
회원정보 수정 관련 null처리하였습니다. 선생님의 자기소개 등은 null이나 빈칸이 들어가도 된다고 생각하였지만, name과 email은 빈칸이 들어가면 안된다고 생각하여 임의로 처리해주었습니다. 한 번 검토 부탁드립니다.
<br><br>
10분
<br><br>
null처리 관련해서 꼭 조언해주세용
<br><br>
<br><br>
<hr>
=> 커리큘럼 조회/검색 페이징 추가, 회원정보 수정관련 null처리, swagger문서 작성

src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumAddRequest.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumDetailResponse.java, src/main/java/com/twentyone/steachserver/domain/curriculum/model/Curriculum.java, src/main/java/com/twentyone/steachserver/domain/curriculum/model/CurriculumDetail.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumService.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/member/model/Teacher.java, src/main/java/com/twentyone/steachserver/util/DateTimeUtil.java, src/main/java/com/twentyone/steachserver/util/WeekdayBitmaskUtil.java
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> API통신 중 변경사항 반영

build.gradle, src/main/java/com/twentyone/steachserver/config/ConstructConfiguration.java, src/main/java/com/twentyone/steachserver/config/security/SecurityConfiguration.java, src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthCodeController.java, src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthController.java, src/main/java/com/twentyone/steachserver/domain/classroom/controller/ClassroomController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumSearchRepository.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/member/memberController/StudentController.java, src/main/java/com/twentyone/steachserver/domain/member/memberController/TeacherController.java, src/test/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImplTest.java, src/test/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceIntegrationTest.java
- 테스트 코드 수정
- 테스트 코드에 사용할 테스트 DB submodule과 합세하여 연결
<br><br>
이전 commit들 한번 더 들어왔으니 무시해주세요
기존 테스트 코드 Date로 비교하던것 이번에 LocalDate으로 바뀌면서 형식 변경
LocalDate와 LocalTime의 특유의 형식으로 인한 문제 formatter로 해결
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> test: 테스트 DB 설정 및 curriculum 테스트 수정

src/main/java/com/twentyone/steachserver/config/ConstructConfiguration.java, src/main/java/com/twentyone/steachserver/domain/classroom/repository/ClassroomQueryRepository.java, src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumSearchRepository.java, src/main/java/com/twentyone/steachserver/domain/lecture/repository/LectureQueryRepository.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/repository/StudentLectureQueryRepository.java
- 사용되지 않는 메서드 수정
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> Fix: 사용되지 않는 메서드 수정

build.gradle, src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthController.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/MemberCheckPasswordRequestDto.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/MemberCheckPasswordResponseDto.java, src/main/java/com/twentyone/steachserver/domain/auth/service/AuthService.java, src/main/java/com/twentyone/steachserver/domain/auth/service/AuthServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumAddRequest.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/member/dto/TeacherInfoRequest.java, src/test/java/com/twentyone/steachserver/auth/WithAuthTeacher.java, src/test/java/com/twentyone/steachserver/auth/WithMockCustomUserSecurityContextFactory.java, src/test/java/com/twentyone/steachserver/domain/IntegrationTests.java, src/test/java/com/twentyone/steachserver/domain/TempTest.java
- 코드 일부 작성 및 비밀번호 확인 로직 추가
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> test 코드 일부 작성 및 비밀번호 확인 로직 추가

src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumIncludesStudentDto.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumIncludesStudentListResponseDto.java, src/main/java/com/twentyone/steachserver/domain/curriculum/model/CurriculumDetail.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumService.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/member/memberController/StudentController.java, src/main/java/com/twentyone/steachserver/domain/member/memberController/TeacherController.java, src/main/java/com/twentyone/steachserver/domain/studentCurriculum/dto/IsApplyForCurriculumResponseDto.java, src/main/java/com/twentyone/steachserver/domain/studentCurriculum/repository/StudentCurriculumRepository.java
- 학생의 강의 취소 메서드 추가
- 학생의 수강 신청 여부 로직 추가
- 강의 신청 
<br><br>
프론트의 요청에 의한 작성
<br><br>
5m
<br><br>
학생의 수강 신청 여부 로직 추가 부분
커리큘럼 조회 시에 필요한 로직인데
지금은 api 따로 분리해서 뒀는데 하나로 합쳐도 된다고 생각되면 합쳐주세요!!
<br><br>
<br><br>
<hr>
=> 사용자와 강의 사이의 통신 기능 추가 

src/main/java/com/twentyone/steachserver/domain/lecture/controller/LectureController.java, src/main/java/com/twentyone/steachserver/domain/lecture/dto/update/UpdateLectureRequestDto.java, src/main/java/com/twentyone/steachserver/domain/lecture/model/Lecture.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java
강의 시간 수정가능하게 변경
<br><br>
프론트 요청
<br><br>
1분
<br><br>
<br><br>
<br><br>
<hr>
=> feat: 강의 시간도 수정가능하도록 변경

src/main/java/com/twentyone/steachserver/config/WebConfig.java, src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/enums/CurriculumCategory.java, src/main/resources/sql/finalSchema.sql, src/test/java/com/twentyone/steachserver/TestScenario1.java, src/test/java/com/twentyone/steachserver/acceptance/MainAcceptanceTest.java, src/test/java/com/twentyone/steachserver/integration/curriculum/controller/CurriculumControllerIntegrationTest.java, src/test/java/com/twentyone/steachserver/integration/curriculum/service/CurriculumServiceIntegrationTest.java, src/test/java/com/twentyone/steachserver/integration/quiz/service/QuizIntegrationTest.java, src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumRedisServiceTest.java, src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumServiceImplTest.java
- [ X Label을 지정했나요?
변경!
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 커리큘럼 카테고리 종류 변경 EDUCATION -> SOCIAL 

build.gradle, src/test/java/com/twentyone/steachserver/TestScenario1.java, src/test/java/com/twentyone/steachserver/acceptance/MainAcceptanceTest.java, src/test/java/com/twentyone/steachserver/integration/curriculum/controller/CurriculumControllerIntegrationTest.java, src/test/java/com/twentyone/steachserver/integration/curriculum/service/CurriculumServiceIntegrationTest.java, src/test/java/com/twentyone/steachserver/integration/quiz/service/QuizIntegrationTest.java, src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumRealRedisServiceTest.java, src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumRedisServiceTest.java, src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumServiceImplTest.java
- 
<br><br>
<br><br>
4m
<br><br>
<br><br>
<br><br>
<hr>
=> 카테고리 변경으로 인한 테스트 충돌 해결 

Dockerfile, Dockerfile_nginx, Jenkinsfile, docker-compose.prod.yml, nginx.conf, src/main/java/com/twentyone/steachserver/config/WebConfig.java, src/main/java/com/twentyone/steachserver/config/security/SecurityConfiguration.java
- nginx 감싸서 서버 배포 완료
- 트래픽 처리 가능. 
<br><br>
1. nginx로 감싸서 jenkins 서버 올리기
- docker-compose.yml이용
2. jenkins UI 초기 설정
3. 젠킨스 서버의 Docker 소켓 마운트 확인
3.1. 도커 데몬 실행 확인
4. 젠킨스 서버 내부 최신버전 docker-compose 다운로드
5. 젠킨스 서버 플러그인 설치 (Docker Pipeline)
6. 깃허브 pat 생성 (orga 관련 설정 확인)
7. 젠킨스 UI에서 github 통신 설정
8. 젠킨스 Job 설정
9. 깃허브 웹훅 설정
10. 젠킨스 서버 내부에 [docker.io](http://docker.io/) 설치
11. jenkins 사용자를 Docker 그룹에 추가
12. Jenkins 컨테이너에서 사용자(?) docker.sock 권한 문제 해결
13. ssh 자격증명 등록(해야하는지 잘 모르겠음) (젠킨스 파일에서는 안 쓰는데 저장해둔 ssh키를 자동으로 인증에 사용하는지 모르겠음)
1. 브랜치 설정
2. 서브모듈 설정
3. 도커 버전 확인
4. 도커 빌드 관련 권한 설정 및 server 도커 이미지 빌드
5. 도커 컴포즈 버전 확인
6. 기존 도커 컴포즈 내리기
7. 도커 …
=> nginx 감싸서 서버 배포 완료

src/main/java/com/twentyone/steachserver/domain/lecture/repository/LectureRepository.java, src/main/java/com/twentyone/steachserver/domain/quiz/controller/QuizController.java, src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizResponseDto.java, src/main/java/com/twentyone/steachserver/domain/quiz/model/Quiz.java, src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizService.java, src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java, src/test/java/com/twentyone/steachserver/integration/quiz/service/QuizIntegrationTest.java
퀴즈 여러 개 수정기능 구현했습니다.
<br><br>
퀴즈 여러 개 수정기능 구현했습니다. 사실 퀴즈 생성기능이랑 완전히 똑같은 로직입니다.
퀴즈를 리스트로 받기 때문에 어느 부분에서 에러가 발생했는지 알려주기 위한 코드도 작성하였습니다.
<br><br>
10분
<br><br>
<br><br>
<br><br>
<hr>
=> 퀴즈 여러 개 수정기능 구현

src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumService.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/member/dto/TeacherInfoResponse.java, src/main/java/com/twentyone/steachserver/domain/member/memberController/TeacherController.java, src/main/java/com/twentyone/steachserver/domain/member/service/TeacherService.java, src/main/java/com/twentyone/steachserver/domain/member/service/TeacherServiceImpl.java
- 모든 권한으로 선생님의 강의와 정보를 볼 수 있는 로직 추가
<br><br>
- 기존 코드를 최대한 활용하여서 작성
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 모든 권한으로 선생님의 강의와 정보를 볼 수 있는 로직 추가

src/main/java/com/twentyone/steachserver/config/security/SecurityConfiguration.java, src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumDetailResponse.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumService.java, src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/member/dto/TeacherInfoResponse.java, src/main/java/com/twentyone/steachserver/domain/member/memberController/TeacherController.java, src/main/java/com/twentyone/steachserver/domain/member/repository/StudentRepository.java, src/main/java/com/twentyone/steachserver/domain/member/service/StudentService.java, src/main/java/com/twentyone/steachserver/domain/member/service/StudentServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/member/service/TeacherService.java, src/main/java/com/twentyone/steachserver/domain/member/service/TeacherServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/quiz/controller/QuizController.java, src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizRequestDto.java, src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizResponseDto.java, src/main/java/com/twentyone/steachserver/domain/quiz/model/Quiz.java, src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizService.java, src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/repository/StudentQuizRepository.java
- 
<br><br>
문제 선택지를 몇 명의 학생들이 투표했는지 알려주는 api를 만들었습니다.
webRTC단에서 만들 수도 있겠지만, 어떻게 돌아가는 지 몰라서 임시로 디비에서 긁어오도록 구현했어요.
<br><br>
10분
<br><br>
<br><br>
<br><br>
<hr>
=> 퀴즈 관련 API 추가

src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthController.java, src/main/java/com/twentyone/steachserver/domain/auth/dto/CheckUsernameAvailableResponse.java, src/main/java/com/twentyone/steachserver/domain/member/repository/StudentRepository.java, src/main/java/com/twentyone/steachserver/domain/member/repository/TeacherRepository.java, src/main/java/com/twentyone/steachserver/domain/member/service/StudentService.java, src/main/java/com/twentyone/steachserver/domain/member/service/StudentServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/member/service/TeacherService.java, src/main/java/com/twentyone/steachserver/domain/member/service/TeacherServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizRequestDto.java, src/main/java/com/twentyone/steachserver/domain/quiz/model/Quiz.java, src/test/java/com/twentyone/steachserver/TestScenario1.java, src/test/java/com/twentyone/steachserver/integration/quiz/service/QuizIntegrationTest.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 중복확인 API 구현

src/test/java/com/twentyone/steachserver/acceptance/MainAcceptanceTest.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> test: 퀴즈 관련 테스트 에러 해결

Jenkinsfile, docker-compose.grafana.yml, docker-compose.jenkins.yml, docker-compose.nginx.yml, docker-compose.prod.yml
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> rename: network 이름 변경

src/main/java/com/twentyone/steachserver/config/security/SecurityConfiguration.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: 권한 없게 변경

src/main/java/com/twentyone/steachserver/config/security/SecurityConfiguration.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> fix: 이메일 중복체크 권한 검증 해제

src/main/java/com/twentyone/steachserver/domain/auth/service/JwtService.java, src/main/java/com/twentyone/steachserver/domain/quiz/controller/QuizController.java, src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizStatisticDto.java, src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizStudentScoreDto.java, src/main/java/com/twentyone/steachserver/domain/quiz/model/QuizStatistics.java, src/main/java/com/twentyone/steachserver/domain/quiz/repository/QuizStatisticsRepository.java, src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizService.java, src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/service/StudentQuizServiceImpl.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> feat: 강의에 대한 퀴즈 맞춘 순위 설정, 조회 기능 구현

src/main/java/com/twentyone/steachserver/config/WebConfig.java
- cors 추가 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: cors 포트 추가

Jenkinsfile, build.gradle, gradle/wrapper/gradle-wrapper.properties, jacoco.gradle, sonarqube.gradle
- sonarqube 자동화 추가
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> sonarqube 자동화 추가

Jenkinsfile
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: sonarqube 젠킨스 코드 수정

Jenkinsfile
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> fix: sonarqube 젠킨스 코드 수정

Jenkinsfile, alloy-config.alloy, docker-compose.grafana.yml, loki-config.yaml, promtail-config.yaml
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> Grafana loki 추가

docker-compose.prod.yml
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 불필요한 볼륨 삭제 (코드리뷰 없는 pr은 외롭다)

build.gradle
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: 원상 복구

jacoco.gradle
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: 테스트 exec 파일 추가하게 하기

jacoco.gradle
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: 원상복구

jacoco.gradle
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> fix: 에러 해결

jacoco.gradle, sonarqube.gradle
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> fix: jacoco 커버리지 한계 수정

jacoco.gradle
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: jacoco파일 위치 변경

nginx.conf, nginx.front.conf, nginx.past.conf, nginx.server.conf, sonarqube.gradle, src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumDetailByLectureDto.java, src/main/java/com/twentyone/steachserver/domain/lecture/repository/LectureQueryRepository.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 강의 종료 예정 시간 변경

src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumDetailByLectureDto.java, src/main/java/com/twentyone/steachserver/domain/lecture/dto/LectureBeforeStartingResponseDto.java, src/main/java/com/twentyone/steachserver/domain/lecture/repository/LectureQueryRepository.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: 변수 위치 변경

src/main/java/com/twentyone/steachserver/domain/lecture/dto/LectureResponseDto.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: 오타 수정

src/main/java/com/twentyone/steachserver/domain/curriculum/enums/CurriculumCategory.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: 기타를 제외하고 반환

src/main/java/com/twentyone/steachserver/domain/statistic/service/StatisticServiceImpl.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: 로직 에러 변경

Jenkinsfile, docker-compose.kafka.yml, src/main/java/com/twentyone/steachserver/domain/gpt/controller/GPTController.java, src/main/java/com/twentyone/steachserver/domain/gpt/service/GPTService.java, src/main/java/com/twentyone/steachserver/domain/gpt/service/GPTServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/statistic/service/StatisticServiceImpl.java, src/main/java/com/twentyone/steachserver/interfaces/kafka/KafkaProducer.java, src/test/java/com/twentyone/steachserver/TestScenario1.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: 젠킨스 순서 변경

src/main/java/com/twentyone/steachserver/domain/lecture/controller/LectureController.java, src/main/java/com/twentyone/steachserver/domain/lecture/dto/CompletedLecturesByStudentResponseDto.java, src/main/java/com/twentyone/steachserver/domain/lecture/dto/StudentInfoByLectureDto.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureService.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/repository/StudentLectureRepository.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> feat: 학생 별 종료된 강의에 대한 정보 반환 메서드 추가

src/main/java/com/twentyone/steachserver/domain/lecture/controller/LectureController.java, src/main/java/com/twentyone/steachserver/domain/lecture/dto/LectureHistoryResponse.java, src/main/java/com/twentyone/steachserver/domain/lecture/dto/MyLectureHistoryResponse.java, src/main/java/com/twentyone/steachserver/domain/lecture/model/Lecture.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureService.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/quiz/repository/QuizStatisticsRepository.java, src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/repository/StudentQuizRepository.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/service/StudentQuizServiceImpl.java
나의 강의 히스토리 API 생성했습니다. 프론트에서 꼭 필요한 API라서 생성했어요
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 나의 강의 히스토리 API 생성

src/main/java/com/twentyone/steachserver/domain/lecture/dto/LectureHistoryResponse.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java
나의 강의 히스토리 API에 강의 시작시간, 끝나는 시간도 추가
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 나의 강의 히스토리 API에 강의 시작시간, 끝나는 시간도 추가

src/main/java/com/twentyone/steachserver/config/RedisConfig.java, src/main/java/com/twentyone/steachserver/domain/gpt/service/GPTServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/lecture/model/Lecture.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/statistic/service/StatisticServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/repository/StudentLectureQueryRepository.java, src/test/java/com/twentyone/steachserver/SteachTest.java, src/test/java/com/twentyone/steachserver/acceptance/MainAcceptanceTest.java, src/test/java/com/twentyone/steachserver/config/TestRedisConfig.java, src/test/java/com/twentyone/steachserver/helper/DatabaseCleanup.java, src/test/java/com/twentyone/steachserver/integration/auth/controller/TeacherAuthControllerIntegrationTest.java, src/test/java/com/twentyone/steachserver/integration/curriculum/controller/CurriculumControllerIntegrationTest.java, src/test/java/com/twentyone/steachserver/unit/RedisConfigInfoTest.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: print문 삭제

src/main/java/com/twentyone/steachserver/domain/lecture/dto/LectureHistoryResponse.java, src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java
나의 강의 히스토리 API 시간 포맷팅 수정
<br><br>
<br><br>
<br><br>
<br><br>
이걸 2024.08.13 9:00으로 바꿈
<br><br>
<hr>
=> 나의 강의 히스토리 API 시간 포맷팅 수정

src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/repository/StudentQuizRepository.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> fix: jpa Repository 에러 해결

src/main/java/com/twentyone/steachserver/domain/curriculum/service/batch/CurriculumBatchService.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/controller/StudentQuizController.java, src/test/java/com/twentyone/steachserver/TestScenario1.java, src/test/java/com/twentyone/steachserver/acceptance/MainAcceptanceTest.java, src/test/java/com/twentyone/steachserver/helper/ServerManager.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: 주석 제외

src/main/java/com/twentyone/steachserver/domain/studentLecture/controller/StudentLectureController.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/model/StudentLecture.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/service/StudentLectureService.java, src/main/java/com/twentyone/steachserver/domain/studentLecture/service/StudentLectureServiceImpl.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> refactor: 받아오는 값 집중 시간에서 집중하지 않는 시간으로 변경

src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java, src/main/java/com/twentyone/steachserver/domain/studentQuiz/repository/StudentQuizRepository.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 퀴즈 통계 순위 내림차순으로 안나오는 에러 해결

src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizStudentScoreDto.java, src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 퀴즈 통계 순위 랭크 순서 제대로 안나오는 에러 수정

docker-compose.sonarqube.yml
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> feat: soanrqube 실행 파일 추가

src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> 학생 강의 히스토리에서 안 푼 퀴즈가 있을 때 400뜨는 에러 해결

Dockerfile
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> test: pr test

src/main/java/com/twentyone/steachserver/config/WebConfig.java
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>
=> cors 설정 추가
